import datetime
import requests
import string


class DataFetcher:
    """ Class for fetching the data that comes from the NOAA website.
    """

    @staticmethod
    def _build_data_directory_url(file_date: datetime.date) -> string:
        """ Build the name of the directory that the date file will be in on the NOAA website.
        Args:
            file_date: The date that the data was recorded for the file we are looking for
        Returns:
            directory_url: A URL to the directory containing the data file we want
        """
        directory_url = "https://www.ngdc.noaa.gov/dscovr/data/"
        directory_url += str(file_date.year) + "/" + str(file_date.month)

        return directory_url

    @staticmethod
    def _find_file_url(file_date: datetime.date) -> string:
        """ Find the URL for the data file for the day that is specified on the NOAA site. We must
            scan the HTML of the page to find the file. Each file has a start time, end time, and
            post time. The start and end times are always 000000 and 595959 respectively, but the
            post time is unknown, so we must scan the webpage for the file so it can be downloaded.

            The file URL will be of the format (with 4-digit years and 2-digit months and days):

                https://www.ngdc.noaa.gov/dscovr/data/<year>/<month>/oe_fc1_dscovr_s<year><month><day>
                000000_e<year><month><day>595959_p<year><month><day><6-digit-time>_pub.nc.gz

        Args:
            file_date: construct the file name and path
        Returns:
            url_string
        """
        url_string = DataFetcher._build_data_directory_url(file_date)

        file_name_start = "/oe_fc1_dscovr" + "_s" + str(file_date.year) + str(file_date.month) + "000000" \
            + "_e" + str(file_date.year) + str(file_date.month) + "595959" + "_p"

        file_name_end = ""

        for page_line in requests.get(url_string).iter_lines(decode_unicode=True):
            if file_name_start in page_line:
                for i in range(0, len(page_line) - 2):
                    if page_line[i] == "_" and page_line[i + 1] == "p":
                        file_name_end += page_line[i + 2: i + 27]

        if len(file_name_end) == 0:
            raise FileNotFoundError("The data file for that date does not exist")

        url_string += file_name_start + file_name_end

        return url_string

    @staticmethod
    def fetch_file(file_date: datetime.date):
        """ Returns a response from the website when making a GET request for a data file.
        Args:
            file_date: The date for which the data file was generated by NOAA and the one which
                        will be fetched from the NOAA website
        Returns:
            data_file: An HTTPS response that contains the data requested
        """
        raw_data_file = requests.get(DataFetcher._find_file_url(file_date), stream=True).raw

        data_file = open(DataFetcher._find_file_url(file_date), "wb")

        for chunk in raw_data_file.iter_content(chunk_size=128):
            data_file.write(chunk)

        return data_file
